
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import 'swiper/css';
import 'swiper/css/pagination';
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { Toaster } from "@/components/ui/sonner"
import Providers from "@/Providers";
const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Exclusive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <main>
          <Providers>
            <Navbar />
            {children}
            <Toaster />
            <Footer />
          </Providers>

        </main>

      </body>
    </html>
  );
}
